# Generated by Django 5.0.6 on 2024-08-30 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('CANC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CANC_STATUS', models.CharField(max_length=50)),
                ('CANC_REASON', models.CharField(max_length=50)),
                ('CANC_DATESENT', models.DateTimeField()),
                ('CANC_DATECONFIRMED', models.DateTimeField()),
                ('CANC_TOTALREFUND', models.FloatField()),
                ('CANC_TYPE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carinderia',
            fields=[
                ('CARIN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CARIN_NAME', models.CharField(max_length=50)),
                ('CARIN_ADDRESS', models.CharField(max_length=50)),
                ('CARIN_PHONE', models.CharField(max_length=50)),
                ('CARIN_USERNAME', models.CharField(max_length=50)),
                ('CARIN_PASSWORD', models.CharField(max_length=50)),
                ('CARIN_EMAIL', models.EmailField(max_length=50)),
                ('CARIN_IMG_CERT', models.ImageField(blank=True, null=True, upload_to='carinderia/certificates/')),
                ('CARIN_IMG_ID', models.ImageField(blank=True, null=True, upload_to='carinderia/ids/')),
                ('CARIN_IMG_LOC', models.ImageField(blank=True, null=True, upload_to='carinderia/locations/')),
                ('CARIN_IMG_KIT1', models.ImageField(blank=True, null=True, upload_to='carinderia/kitchen1/')),
                ('CARIN_IMG_KIT2', models.ImageField(blank=True, null=True, upload_to='carinderia/kitchen2/')),
                ('CARIN_ACTIVE', models.BooleanField(default=True)),
                ('CARIN_DATECREATED', models.DateField(auto_now_add=True)),
                ('CARIN_LOGO', models.ImageField(blank=True, null=True, upload_to='carinderia/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('GRDL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GRDL_GRADELVL', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('MEAL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MEAL_DAY', models.CharField(max_length=50)),
                ('MEAL_DATE', models.DateField()),
                ('MEAL_SUBTOTAL', models.FloatField()),
                ('MEAL_DLVRSTATUS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('PARENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PARENT_FNAME', models.CharField(max_length=50)),
                ('PARENT_LNAME', models.CharField(max_length=50)),
                ('PARENT_DOB', models.DateField()),
                ('PARENT_PHONE', models.CharField(max_length=15)),
                ('PARENT_ADDRESS', models.CharField(max_length=100)),
                ('PARENT_EMAIL', models.EmailField(max_length=50)),
                ('PARENT_USERNAME', models.CharField(max_length=50)),
                ('PARENT_PASSWORD', models.CharField(max_length=50)),
                ('PARENT_ACTIVE', models.BooleanField(default=True)),
                ('PARENT_DATECREATED', models.DateField(auto_now_add=True)),
                ('PARENT_PROFILE', models.ImageField(blank=True, null=True, upload_to='parent_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('SCHOOL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SCHOOL_NAME', models.CharField(max_length=50)),
                ('SCHOOL_ADDRESS', models.CharField(max_length=50)),
                ('SCHOOL_PHONE', models.CharField(max_length=15)),
                ('SCHOOL_EMAIL', models.EmailField(max_length=50)),
                ('SCHOOL_DATECREATED', models.DateField(auto_now_add=True)),
                ('SCHOOL_ACTIVE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationReceipt',
            fields=[
                ('CANCREC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CANCREC_REF', models.IntegerField()),
                ('CANCREC_TOTAL', models.FloatField()),
                ('CANCREC_DATE', models.DateTimeField()),
                ('CANC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cancellation')),
            ],
        ),
        migrations.CreateModel(
            name='CarinderiaVerification',
            fields=[
                ('VCARIN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('VCARIN_STATUS', models.CharField(max_length=50)),
                ('CARIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.carinderia')),
            ],
        ),
        migrations.CreateModel(
            name='GradeSection',
            fields=[
                ('GRDS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('GRDS_STUDID', models.IntegerField()),
                ('GRDS_FNAME', models.CharField(max_length=50)),
                ('GRDS_LNAME', models.CharField(max_length=50)),
                ('GRDL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('INC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('INC_TOTAL', models.FloatField()),
                ('INC_CARIN', models.FloatField()),
                ('INC_SCHOOL', models.FloatField()),
                ('INC_ADMIN', models.FloatField()),
                ('MEAL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DEL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DEL_STATUS', models.CharField(max_length=50)),
                ('DEL_DAY', models.CharField(max_length=50)),
                ('DEL_DATE', models.DateTimeField()),
                ('MEAL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal')),
            ],
        ),
        migrations.AddField(
            model_name='cancellation',
            name='MEAL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal'),
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('MPLAN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MPLAN_MEALTYPE', models.CharField(max_length=50)),
                ('MPLAN_TOTALPRICE', models.FloatField()),
                ('MPLAN_STATUS', models.CharField(max_length=50)),
                ('CARIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.carinderia')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='MPLAN_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealplan'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='MPLAN_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealplan'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('MENU_ID', models.AutoField(primary_key=True, serialize=False)),
                ('MENU_NAME', models.CharField(max_length=50)),
                ('MENU_DESCRIPT', models.CharField(max_length=250)),
                ('MENU_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MENU_CALORIE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MENU_CARBS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MENU_PROTEIN', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MENU_FATS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MENU_TYPE', models.CharField(max_length=50)),
                ('MENU_MEALTYPE', models.CharField(max_length=50)),
                ('CARINDERIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.carinderia')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ING_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ING_NAME', models.CharField(max_length=50)),
                ('ING_TYPE', models.CharField(max_length=50)),
                ('MENU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('DISH_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DISH_NAME', models.CharField(max_length=50)),
                ('DISH_PRICE', models.FloatField()),
                ('MEAL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal')),
                ('MENU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PAY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PAY_STATUS', models.CharField(max_length=50)),
                ('PAY_DATESENT', models.DateTimeField()),
                ('PAY_DATECONFIRMED', models.DateTimeField()),
                ('PAY_TYPE', models.CharField(max_length=50)),
                ('MPLAN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('REC_ID', models.AutoField(primary_key=True, serialize=False)),
                ('REC_REF', models.IntegerField()),
                ('REC_TOTAL', models.FloatField()),
                ('REC_DATE', models.DateTimeField()),
                ('PAY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.payment')),
            ],
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='SCHOOL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.school'),
        ),
        migrations.CreateModel(
            name='SchoolCarinderia',
            fields=[
                ('SCHCARIN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SCHCARIN_NAME', models.CharField(max_length=50)),
                ('CARIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.carinderia')),
                ('SCHOOL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('STUD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('STUD_FNAME', models.CharField(max_length=50)),
                ('STUD_LNAME', models.CharField(max_length=50)),
                ('STUD_GRADELVL', models.IntegerField()),
                ('STUD_BIRTHDATE', models.DateField()),
                ('STUD_SECTION', models.CharField(max_length=50)),
                ('STUD_STUDID', models.IntegerField()),
                ('STUD_ADDRESS', models.CharField(max_length=100)),
                ('STUD_PHONE', models.CharField(max_length=15)),
                ('STUD_ACTIVE', models.BooleanField(default=True)),
                ('STUD_DATECREATED', models.DateTimeField(auto_now_add=True)),
                ('STUD_PROFILE', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('PARENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.parent')),
                ('SCHOOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.school')),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='STUD_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.student'),
        ),
        migrations.CreateModel(
            name='StudentSurvey',
            fields=[
                ('SS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SS_AGE', models.IntegerField()),
                ('SS_WEIGHT', models.FloatField()),
                ('SS_HEIGHT', models.FloatField()),
                ('SS_BMI', models.FloatField()),
                ('SS_SEX', models.CharField(max_length=50)),
                ('SS_ALLERGENS', models.CharField(max_length=50)),
                ('SS_FOODPREF', models.CharField(max_length=50)),
                ('SS_DIETARY', models.CharField(max_length=50)),
                ('SS_ACTLVL', models.CharField(max_length=50)),
                ('STUD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.student')),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('ALRGN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ALRGN_TYPE', models.CharField(max_length=50)),
                ('ALRGN_NAME', models.CharField(max_length=50)),
                ('SS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.studentsurvey')),
            ],
        ),
    ]
